use std::collections::HashMap;
use std::path::Path;

use serde::Deserialize;

// ── raw JSON structs ───────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
pub struct RawQtType {
    pub parent: Option<String>,
    pub properties: HashMap<String, String>,
    pub signals: HashMap<String, Vec<String>>,
    pub methods: HashMap<String, Vec<String>>,
    pub enums: HashMap<String, Vec<String>>,
}

// ── Qt type database ───────────────────────────────────────────────────────

pub struct QtTypeDb {
    types: HashMap<String, RawQtType>,
}

impl QtTypeDb {
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        let raw: HashMap<String, serde_json::Value> = serde_json::from_str(json)?;
        let mut types = HashMap::new();
        for (key, val) in raw {
            if key.starts_with('_') {
                continue; // skip _comment etc.
            }
            let qt_type: RawQtType = serde_json::from_value(val)?;
            types.insert(key, qt_type);
        }
        Ok(Self { types })
    }

    pub fn has_type(&self, name: &str) -> bool {
        self.types.contains_key(name)
    }

    pub fn all_properties(&self, type_name: &str) -> HashMap<String, String> {
        let mut result = HashMap::new();
        self.collect_properties(type_name, &mut result);
        result
    }

    pub fn all_signals(&self, type_name: &str) -> HashMap<String, Vec<String>> {
        let mut result = HashMap::new();
        self.collect_signals(type_name, &mut result);
        result
    }

    pub fn all_methods(&self, type_name: &str) -> HashMap<String, Vec<String>> {
        let mut result = HashMap::new();
        self.collect_methods(type_name, &mut result);
        result
    }

    fn collect_properties(&self, type_name: &str, out: &mut HashMap<String, String>) {
        let Some(qt_type) = self.types.get(type_name) else {
            return;
        };
        if let Some(parent) = &qt_type.parent {
            self.collect_properties(parent, out);
        }
        for (k, v) in &qt_type.properties {
            out.insert(k.clone(), v.clone());
        }
    }

    fn collect_signals(&self, type_name: &str, out: &mut HashMap<String, Vec<String>>) {
        let Some(qt_type) = self.types.get(type_name) else {
            return;
        };
        if let Some(parent) = &qt_type.parent {
            self.collect_signals(parent, out);
        }
        for (k, v) in &qt_type.signals {
            out.insert(k.clone(), v.clone());
        }
    }

    fn collect_methods(&self, type_name: &str, out: &mut HashMap<String, Vec<String>>) {
        let Some(qt_type) = self.types.get(type_name) else {
            return;
        };
        if let Some(parent) = &qt_type.parent {
            self.collect_methods(parent, out);
        }
        for (k, v) in &qt_type.methods {
            out.insert(k.clone(), v.clone());
        }
    }
}

// ── compile-time embedded databases ───────────────────────────────────────
//
// BUILTIN_QT_TYPES is generated by build.rs from the INCLUDED_QT_TYPES env var.
// It is a &[(&str, &str)] of (version_string, json_content) pairs.

include!(concat!(env!("OUT_DIR"), "/qt_types_builtin.rs"));

/// Returns all Qt version strings compiled into the binary.
pub fn builtin_versions() -> Vec<&'static str> {
    BUILTIN_QT_TYPES.iter().map(|(v, _)| *v).collect()
}

/// Load a built-in (compile-time embedded) database for the given Qt version string.
///
/// Returns `Err` if that version was not compiled in.
/// Use [`builtin_versions`] to list available versions.
pub fn load_builtin_db(version: &str) -> Result<QtTypeDb, String> {
    for (v, json) in BUILTIN_QT_TYPES {
        if *v == version {
            return QtTypeDb::from_json(json).map_err(|e| format!("Qt {version} embedded data is invalid: {e}"));
        }
    }
    Err(format!(
        "Qt version '{version}' is not compiled in. \
         Available: {available:?}. \
         Re-build with INCLUDED_QT_TYPES pointing to the right JSON file, \
         or use --qt-types-json to load at runtime.",
        available = builtin_versions()
    ))
}

/// Load the default built-in database (first available version).
///
/// Panics if no Qt version was compiled in.
pub fn load_default_builtin_db() -> QtTypeDb {
    let (version, json) = BUILTIN_QT_TYPES.first().unwrap_or_else(|| {
        panic!(
            "No Qt types compiled in. \
             Re-build with INCLUDED_QT_TYPES=path/to/qt_types_X.Y.Z.json, \
             or pass --qt-types-json at runtime."
        )
    });
    QtTypeDb::from_json(json).unwrap_or_else(|e| panic!("Qt {version} embedded data is invalid: {e}"))
}

/// Load a database from a pre-generated JSON file on disk.
pub fn load_from_json_file(path: &Path) -> Result<QtTypeDb, String> {
    let json = std::fs::read_to_string(path).map_err(|e| format!("Cannot read {path:?}: {e}"))?;
    QtTypeDb::from_json(&json).map_err(|e| format!("Invalid Qt types JSON in {path:?}: {e}"))
}
